stages:
  load_data:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/case_study1.xlsx
      - data/raw/case_study2.xlsx
    outs:
      - data/processed/df1.csv
      - data/processed/df2.csv

  preprocess_data:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/processed/df1.csv
      - data/processed/df2.csv
    outs:
      - data/processed/df1_cleaned.csv
      - data/processed/df2_cleaned.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/df1_cleaned.csv
      - data/processed/df2_cleaned.csv
    outs:
      - data/processed/df_final.csv

  train_models:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/processed/df_final.csv
    outs:
      - models/rf_model.joblib
      - models/xgb_model.joblib
      - models/dt_model.joblib

  evaluate_models:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/rf_model.joblib
      - models/xgb_model.joblib
      - models/dt_model.joblib
    outs:
      - reports/evaluation_report.txt
